grafana:
  enabled: false

influxdb:
  image:
    repository: influxdb
    tag: "1.11"
  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn
  auth:
    database: GarminStats
    username: admin
    password: password
    adminUser: admin
    adminPassword: password
  env:
    - name: INFLUXDB_DB
      value: "{{ .Values.influxdb.auth.database }}"
    - name: INFLUXDB_HTTP_AUTH_ENABLED
      value: "true"

garmin:
  image:
    repository: ghcr.io/arpanghosh8453/garmin-fetch-data
    tag: v0.3.0
  port: 8000
  tokens:
    persistence:
      enabled: true
      size: 100Mi
      storageClass: longhorn
  credentials:
    email: "CHANGE_ME"
    base64Password: "CHANGE_ME"
  env:
    - name: INFLUXDB_HOST
      value: "{{ .Release.Name }}-influxdb"
    - name: INFLUXDB_PORT
      value: "8086"
    - name: INFLUXDB_DATABASE
      value: "{{ .Values.influxdb.auth.database }}"
    - name: INFLUXDB_ENDPOINT_IS_HTTP
      value: "True"
    - name: INFLUXDB_VERSION
      value: "1"
    - name: ALWAYS_PROCESS_FIT_FILES
      value: "True"
    - name: FETCH_INTERVAL
      value: "15min"
    - name: USER_TIMEZONE
      value: "Australia/Sydney"
    - name: GARMINCONNECT_IS_CN
      value: "True"
